In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# 경고 무시 설정
import warnings
warnings.filterwarnings(action='ignore')

# 한글 깨짐 방지
plt.rcParams['font.family'] = 'Malgun Gothic'
# 마이너스 부호 깨짐 방지
plt.rcParams['axes.unicode_minus'] = False

## 데이터 전처리(연도별 전기사용량)

### 2020년도 데이터

In [2]:
df1 = pd.read_csv('./e_2020.csv')
# 컬럼명 앞뒤 공백 제거
df1.columns = df1.columns.str.strip()
df1

                              대지위치  법정동코드  번  지    사용년월  사용량(KWh)
0              경상북도 포항시 남구 상도동 1-9  10100  1  9  202001      1149
1              경상북도 포항시 남구 상도동 1-9  10100  1  9  202002      1122
2              경상북도 포항시 남구 상도동 1-9  10100  1  9  202003       764
3              경상북도 포항시 남구 상도동 1-9  10100  1  9  202004       718
4                                '  10100  1  9  202005       633
...                            ...    ... .. ..     ...       ...
105238  경상북도 포항시 남구 호미곶면 대동배리 산3-4  35024  3  4  202008       492
105239  경상북도 포항시 남구 호미곶면 대동배리 산3-4  35024  3  4  202009       328
105240  경상북도 포항시 남구 호미곶면 대동배리 산3-4  35024  3  4  202010       196
105241  경상북도 포항시 남구 호미곶면 대동배리 산3-4  35024  3  4  202011       213
105242  경상북도 포항시 남구 호미곶면 대동배리 산3-4  35024  3  4  202012       225

[105243 rows x 6 columns]

In [3]:
# 1. '대지위치' 컬럼 삭제
df01 = df1.drop(columns=['대지위치'])

# 2. 법정동코드 + 번 + 지 를 합쳐서 'code' 컬럼 생성
# 문자열 연산을 통해 하나로 합칩니다.
df01['code'] = df1['법정동코드'].astype(str) + '-' + \
                     df1['번'].astype(str) + '-' + \
                     df1['지'].astype(str)
    
# 3. 합치기에 사용된 기존 컬럼 삭제 (선택 사항)
df01 = df01.drop(columns=['법정동코드', '번', '지'])

# 4. 사용년월에서 month 추출 및 사용년월(year 포함) 삭제
# 문자열로 변환 후 뒤에서 두 자리만 가져옵니다.
df01['year'] = df1['사용년월'].astype(str).str[:4]
df01['month'] = df1['사용년월'].astype(str).str[-2:]
df01 = df01.drop(columns=['사용년월'])

# 5. 사용량(KWh)을 계산을 위해 숫자형으로 변환
df01['e_amount'] = pd.to_numeric(df1['사용량(KWh)'], errors='coerce').fillna(0)

# 6. 필요한 컬럼만 선택
df01 = df01[['code', 'year','month', 'e_amount']]
df01

             code  year month  e_amount
0       10100-1-9  2020    01      1149
1       10100-1-9  2020    02      1122
2       10100-1-9  2020    03       764
3       10100-1-9  2020    04       718
4       10100-1-9  2020    05       633
...           ...   ...   ...       ...
105238  35024-3-4  2020    08       492
105239  35024-3-4  2020    09       328
105240  35024-3-4  2020    10       196
105241  35024-3-4  2020    11       213
105242  35024-3-4  2020    12       225

[105243 rows x 4 columns]

In [4]:
df01.to_csv('e_code_2020.csv', index=False, encoding='utf-8-sig')

### 2021년도 데이터

In [5]:
df2 = pd.read_csv('./e_2021.csv')
# 컬럼명 앞뒤 공백 제거
df2.columns = df2.columns.str.strip()
df2

                              대지위치  법정동코드  번  지    사용년월  사용량(KWh)
0              경상북도 포항시 남구 상도동 1-9  10100  1  9  202101      1426
1              경상북도 포항시 남구 상도동 1-9  10100  1  9  202102      1396
2              경상북도 포항시 남구 상도동 1-9  10100  1  9  202103      1210
3              경상북도 포항시 남구 상도동 1-9  10100  1  9  202104      1233
4              경상북도 포항시 남구 상도동 1-9  10100  1  9  202105       942
...                            ...    ... .. ..     ...       ...
106255  경상북도 포항시 남구 호미곶면 대동배리 산3-4  35024  3  4  202108       181
106256  경상북도 포항시 남구 호미곶면 대동배리 산3-4  35024  3  4  202109       166
106257                         NaN  35024  3  4  202110       182
106258  경상북도 포항시 남구 호미곶면 대동배리 산3-4  35024  3  4  202111       159
106259                         NaN  35024  3  4  202112       203

[106260 rows x 6 columns]

In [6]:
# 1. '대지위치' 컬럼 삭제
df02 = df2.drop(columns=['대지위치'])

# 2. 법정동코드 + 번 + 지 를 합쳐서 'code' 컬럼 생성
# 문자열 연산을 통해 하나로 합칩니다.
df02['code'] = df2['법정동코드'].astype(str) + '-' + \
                     df2['번'].astype(str) + '-' + \
                     df2['지'].astype(str)
    
# 3. 합치기에 사용된 기존 컬럼 삭제 (선택 사항)
df02 = df02.drop(columns=['법정동코드', '번', '지'])

# 4. 사용년월에서 month 추출 및 사용년월(year 포함) 삭제
# 문자열로 변환 후 뒤에서 두 자리만 가져옵니다.
df02['year'] = df2['사용년월'].astype(str).str[:4]
df02['month'] = df2['사용년월'].astype(str).str[-2:]
df02 = df02.drop(columns=['사용년월'])

# 5. 사용량(KWh)을 계산을 위해 숫자형으로 변환
df02['e_amount'] = pd.to_numeric(df2['사용량(KWh)'], errors='coerce').fillna(0)

# 6. 필요한 컬럼만 선택
df02 = df02[['code', 'year', 'month', 'e_amount']]
df02

             code  year month  e_amount
0       10100-1-9  2021    01      1426
1       10100-1-9  2021    02      1396
2       10100-1-9  2021    03      1210
3       10100-1-9  2021    04      1233
4       10100-1-9  2021    05       942
...           ...   ...   ...       ...
106255  35024-3-4  2021    08       181
106256  35024-3-4  2021    09       166
106257  35024-3-4  2021    10       182
106258  35024-3-4  2021    11       159
106259  35024-3-4  2021    12       203

[106260 rows x 4 columns]

In [7]:
df02.to_csv('e_code_2021.csv', index=False, encoding='utf-8-sig')

### 2022년도 데이터

In [8]:
df3 = pd.read_csv('./e_2022.csv')
# 컬럼명 앞뒤 공백 제거
df3.columns = df3.columns.str.strip()
df3

                              대지위치  법정동코드  번  지    사용년월  사용량(KWh)
0              경상북도 포항시 남구 상도동 1-9  10100  1  9  202201      1528
1              경상북도 포항시 남구 상도동 1-9  10100  1  9  202202      1478
2              경상북도 포항시 남구 상도동 1-9  10100  1  9  202203      1469
3              경상북도 포항시 남구 상도동 1-9  10100  1  9  202204      1272
4              경상북도 포항시 남구 상도동 1-9  10100  1  9  202205       885
...                            ...    ... .. ..     ...       ...
107724  경상북도 포항시 남구 호미곶면 대동배리 산3-4  35024  3  4  202208       176
107725  경상북도 포항시 남구 호미곶면 대동배리 산3-4  35024  3  4  202209       167
107726  경상북도 포항시 남구 호미곶면 대동배리 산3-4  35024  3  4  202210       192
107727  경상북도 포항시 남구 호미곶면 대동배리 산3-4  35024  3  4  202211       197
107728  경상북도 포항시 남구 호미곶면 대동배리 산3-4  35024  3  4  202212       248

[107729 rows x 6 columns]

In [9]:
# 1. '대지위치' 컬럼 삭제
df03 = df3.drop(columns=['대지위치'])

# 2. 법정동코드 + 번 + 지 를 합쳐서 'code' 컬럼 생성
# 문자열 연산을 통해 하나로 합칩니다.
df03['code'] = df3['법정동코드'].astype(str) + '-' + \
                     df3['번'].astype(str) + '-' + \
                     df3['지'].astype(str)
    
# 3. 합치기에 사용된 기존 컬럼 삭제 (선택 사항)
df03 = df03.drop(columns=['법정동코드', '번', '지'])

# 4. 사용년월에서 month 추출 및 사용년월(year 포함) 삭제
# 문자열로 변환 후 뒤에서 두 자리만 가져옵니다.
df03['year'] = df3['사용년월'].astype(str).str[:4]
df03['month'] = df3['사용년월'].astype(str).str[-2:]
df03 = df03.drop(columns=['사용년월'])

# 5. 사용량(KWh)을 계산을 위해 숫자형으로 변환
df03['e_amount'] = pd.to_numeric(df3['사용량(KWh)'], errors='coerce').fillna(0)

# 6. 필요한 컬럼만 선택
df03 = df03[['code', 'year', 'month', 'e_amount']]
df03

             code  year month  e_amount
0       10100-1-9  2022    01      1528
1       10100-1-9  2022    02      1478
2       10100-1-9  2022    03      1469
3       10100-1-9  2022    04      1272
4       10100-1-9  2022    05       885
...           ...   ...   ...       ...
107724  35024-3-4  2022    08       176
107725  35024-3-4  2022    09       167
107726  35024-3-4  2022    10       192
107727  35024-3-4  2022    11       197
107728  35024-3-4  2022    12       248

[107729 rows x 4 columns]

In [10]:
df03.to_csv('e_code_2022.csv', index=False, encoding='utf-8-sig')

### 2023년도 데이터

In [11]:
df4 = pd.read_csv('./e_2023.csv')
# 컬럼명 앞뒤 공백 제거
df4.columns = df4.columns.str.strip()
df4

                              대지위치  법정동코드  번  지    사용년월  사용량(KWh)
0              경상북도 포항시 남구 상도동 1-9  10100  1  9  202301      1144
1              경상북도 포항시 남구 상도동 1-9  10100  1  9  202302      1405
2              경상북도 포항시 남구 상도동 1-9  10100  1  9  202303      1263
3              경상북도 포항시 남구 상도동 1-9  10100  1  9  202304      1112
4              경상북도 포항시 남구 상도동 1-9  10100  1  9  202305      1140
...                            ...    ... .. ..     ...       ...
110324  경상북도 포항시 남구 호미곶면 대동배리 산3-4  35024  3  4  202308       125
110325  경상북도 포항시 남구 호미곶면 대동배리 산3-4  35024  3  4  202309        75
110326  경상북도 포항시 남구 호미곶면 대동배리 산3-4  35024  3  4  202310       142
110327  경상북도 포항시 남구 호미곶면 대동배리 산3-4  35024  3  4  202311        37
110328  경상북도 포항시 남구 호미곶면 대동배리 산3-4  35024  3  4  202312         1

[110329 rows x 6 columns]

In [12]:
# 1. '대지위치' 컬럼 삭제
df04 = df4.drop(columns=['대지위치'])

# 2. 법정동코드 + 번 + 지 를 합쳐서 'code' 컬럼 생성
# 문자열 연산을 통해 하나로 합칩니다.
df04['code'] = df4['법정동코드'].astype(str) + '-' + \
                     df4['번'].astype(str) + '-' + \
                     df4['지'].astype(str)
    
# 3. 합치기에 사용된 기존 컬럼 삭제 (선택 사항)
df04 = df04.drop(columns=['법정동코드', '번', '지'])

# 4. 사용년월에서 month 추출 및 사용년월(year 포함) 삭제
# 문자열로 변환 후 뒤에서 두 자리만 가져옵니다.
df04['year'] = df4['사용년월'].astype(str).str[:4]
df04['month'] = df4['사용년월'].astype(str).str[-2:]
df04 = df04.drop(columns=['사용년월'])

# 5. 사용량(KWh)을 계산을 위해 숫자형으로 변환
df04['e_amount'] = pd.to_numeric(df4['사용량(KWh)'], errors='coerce').fillna(0)

# 6. 필요한 컬럼만 선택
df04 = df04[['code', 'year', 'month', 'e_amount']]
df04

             code  year month  e_amount
0       10100-1-9  2023    01      1144
1       10100-1-9  2023    02      1405
2       10100-1-9  2023    03      1263
3       10100-1-9  2023    04      1112
4       10100-1-9  2023    05      1140
...           ...   ...   ...       ...
110324  35024-3-4  2023    08       125
110325  35024-3-4  2023    09        75
110326  35024-3-4  2023    10       142
110327  35024-3-4  2023    11        37
110328  35024-3-4  2023    12         1

[110329 rows x 4 columns]

In [13]:
df04.to_csv('e_code_2023.csv', index=False, encoding='utf-8-sig')

### 2024년도 데이터

In [14]:
df5 = pd.read_csv('./e_2024.csv')
# 컬럼명 앞뒤 공백 제거
df5.columns = df5.columns.str.strip()
df5

                              대지위치  법정동코드  번  지    사용년월  사용량(KWh)
0              경상북도 포항시 남구 상도동 1-9  10100  1  9  202401      3255
1              경상북도 포항시 남구 상도동 1-9  10100  1  9  202402      2882
2              경상북도 포항시 남구 상도동 1-9  10100  1  9  202403      2408
3              경상북도 포항시 남구 상도동 1-9  10100  1  9  202404      1511
4              경상북도 포항시 남구 상도동 1-9  10100  1  9  202405      1023
...                            ...    ... .. ..     ...       ...
112654  경상북도 포항시 남구 호미곶면 대동배리 산3-4  35024  3  4  202401         2
112655  경상북도 포항시 남구 호미곶면 대동배리 산3-4  35024  3  4  202403         1
112656  경상북도 포항시 남구 호미곶면 대동배리 산3-4  35024  3  4  202406         1
112657  경상북도 포항시 남구 호미곶면 대동배리 산3-4  35024  3  4  202408         1
112658  경상북도 포항시 남구 호미곶면 대동배리 산3-4  35024  3  4  202409         1

[112659 rows x 6 columns]

In [15]:
# 1. '대지위치' 컬럼 삭제
df05 = df5.drop(columns=['대지위치'])

# 2. 법정동코드 + 번 + 지 를 합쳐서 'code' 컬럼 생성
# 문자열 연산을 통해 하나로 합칩니다.
df05['code'] = df5['법정동코드'].astype(str) + '-' + \
                     df5['번'].astype(str) + '-' + \
                     df5['지'].astype(str)
    
# 3. 합치기에 사용된 기존 컬럼 삭제 (선택 사항)
df05 = df05.drop(columns=['법정동코드', '번', '지'])

# 4. 사용년월에서 month 추출 및 사용년월(year 포함) 삭제
# 문자열로 변환 후 뒤에서 두 자리만 가져옵니다.
df05['year'] = df5['사용년월'].astype(str).str[:4]
df05['month'] = df5['사용년월'].astype(str).str[-2:]
df05 = df05.drop(columns=['사용년월'])

# 5. 사용량(KWh)을 계산을 위해 숫자형으로 변환
df05['e_amount'] = pd.to_numeric(df5['사용량(KWh)'], errors='coerce').fillna(0)

# 6. 필요한 컬럼만 선택
df05 = df05[['code', 'year', 'month', 'gas_amount']]
df05

KeyError: "['gas_amount'] not in index"

### 2025년도 데이터

In [ ]:
df6 = pd.read_csv('./e_2025.csv')
# 컬럼명 앞뒤 공백 제거
df6.columns = df6.columns.str.strip()
df6

In [ ]:
# 1. '대지위치' 컬럼 삭제
df06 = df6.drop(columns=['대지위치'])

# 2. 법정동코드 + 번 + 지 를 합쳐서 'code' 컬럼 생성
# 문자열 연산을 통해 하나로 합칩니다.
df06['code'] = df6['법정동코드'].astype(str) + '-' + \
                     df6['번'].astype(str) + '-' + \
                     df6['지'].astype(str)
    
# 3. 합치기에 사용된 기존 컬럼 삭제 (선택 사항)
df06 = df06.drop(columns=['법정동코드', '번', '지'])

# 4. 사용년월에서 month 추출 및 사용년월(year 포함) 삭제
# 문자열로 변환 후 뒤에서 두 자리만 가져옵니다.
df06['year'] = df6['사용년월'].astype(str).str[:4]
df06['month'] = df6['사용년월'].astype(str).str[-2:]
df06 = df06.drop(columns=['사용년월'])

# 5. 사용량(KWh)을 계산을 위해 숫자형으로 변환
df06['e_amount'] = pd.to_numeric(df6['사용량(KWh)'], errors='coerce').fillna(0)

# 6. 필요한 컬럼만 선택
df06 = df06[['code', 'year', 'month', 'gas_amount']]
df06