In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# 경고 무시 설정
import warnings
warnings.filterwarnings(action='ignore')

# 한글 깨짐 방지
plt.rcParams['font.family'] = 'Malgun Gothic'
# 마이너스 부호 깨짐 방지
plt.rcParams['axes.unicode_minus'] = False

## 데이터 전처리(연도별 가스사용량)

### 2020년도 데이터

In [2]:
df1 = pd.read_csv('./gas_2020.csv')
# 컬럼명 앞뒤 공백 제거
df1.columns = df1.columns.str.strip()
df1

                           대지위치  법정동코드   번   지    사용년월  사용량(KWh)
0          경상북도 포항시 남구 상도동 1-13  10100   1  13  202010        94
1          경상북도 포항시 남구 상도동 1-22  10100   1  22  202001       859
2          경상북도 포항시 남구 상도동 1-22  10100   1  22  202002      1295
3          경상북도 포항시 남구 상도동 1-22  10100   1  22  202003      1236
4          경상북도 포항시 남구 상도동 1-22  10100   1  22  202004       777
...                         ...    ...  ..  ..     ...       ...
29397  경상북도 포항시 남구 동해면 석리 18-11  32025  18  11  202006     46285
29398  경상북도 포항시 남구 동해면 석리 18-11  32025  18  11  202007     26954
29399  경상북도 포항시 남구 동해면 석리 18-11  32025  18  11  202008     22362
29400  경상북도 포항시 남구 동해면 석리 18-11  32025  18  11  202011     78156
29401  경상북도 포항시 남구 동해면 석리 18-11  32025  18  11  202012    142342

[29402 rows x 6 columns]

In [3]:
# 1. '대지위치' 컬럼 삭제
df01 = df1.drop(columns=['대지위치'])

# 2. 법정동코드 + 번 + 지 를 합쳐서 'code' 컬럼 생성
# 문자열 연산을 통해 하나로 합칩니다.
df01['code'] = df1['법정동코드'].astype(str) + '-' + \
                     df1['번'].astype(str) + '-' + \
                     df1['지'].astype(str)
    
# 3. 합치기에 사용된 기존 컬럼 삭제 (선택 사항)
df01 = df01.drop(columns=['법정동코드', '번', '지'])

# 4. 사용년월에서 month 추출 및 사용년월(year 포함) 삭제
# 문자열로 변환 후 뒤에서 두 자리만 가져옵니다.
df01['year'] = df1['사용년월'].astype(str).str[:4]
df01['month'] = df1['사용년월'].astype(str).str[-2:]
df01 = df01.drop(columns=['사용년월'])

# 5. 사용량(KWh)을 계산을 위해 숫자형으로 변환
df01['gas_amount'] = pd.to_numeric(df1['사용량(KWh)'], errors='coerce').fillna(0)

# 6. 필요한 컬럼만 선택
df01 = df01[['code', 'year','month', 'gas_amount']]
df01

              code  year month  gas_amount
0       10100-1-13  2020    10          94
1       10100-1-22  2020    01         859
2       10100-1-22  2020    02        1295
3       10100-1-22  2020    03        1236
4       10100-1-22  2020    04         777
...            ...   ...   ...         ...
29397  32025-18-11  2020    06       46285
29398  32025-18-11  2020    07       26954
29399  32025-18-11  2020    08       22362
29400  32025-18-11  2020    11       78156
29401  32025-18-11  2020    12      142342

[29402 rows x 4 columns]

In [4]:
df01.to_csv('gas_code_2020.csv', index=False, encoding='utf-8-sig')

In [5]:
# df01 = df01.groupby(['code'], as_index=False)['gas_amount'].sum()
# df01

### 2021년도 데이터

In [6]:
df2 = pd.read_csv('./gas_2021.csv')
df2.columns = df1.columns.str.strip()
df2

                           대지위치  법정동코드   번   지    사용년월  사용량(KWh)
0          경상북도 포항시 남구 상도동 1-22  10100   1  22  202101      1025
1          경상북도 포항시 남구 상도동 1-22  10100   1  22  202102      1348
2          경상북도 포항시 남구 상도동 1-22  10100   1  22  202103      1230
3          경상북도 포항시 남구 상도동 1-22  10100   1  22  202104       952
4          경상북도 포항시 남구 상도동 1-22  10100   1  22  202105       661
...                         ...    ...  ..  ..     ...       ...
30733  경상북도 포항시 남구 동해면 석리 18-11  32025  18  11  202108     24178
30734  경상북도 포항시 남구 동해면 석리 18-11  32025  18  11  202109     25963
30735                       NaN  32025  18  11  202110     42493
30736  경상북도 포항시 남구 동해면 석리 18-11  32025  18  11  202111     93555
30737                       NaN  32025  18  11  202112    155554

[30738 rows x 6 columns]

In [7]:
# 1. '대지위치' 컬럼 삭제
df02 = df2.drop(columns=['대지위치'])

# 2. 법정동코드 + 번 + 지 를 합쳐서 'code' 컬럼 생성
# 문자열 연산을 통해 하나로 합칩니다.
df02['code'] = df2['법정동코드'].astype(str) + '-' + \
                     df2['번'].astype(str) + '-' + \
                     df2['지'].astype(str)
    
# 3. 합치기에 사용된 기존 컬럼 삭제 (선택 사항)
df02 = df02.drop(columns=['법정동코드', '번', '지'])

# 4. 사용년월에서 month 추출 및 사용년월(year 포함) 삭제
# 문자열로 변환 후 뒤에서 두 자리만 가져옵니다.
df02['year'] = df2['사용년월'].astype(str).str[:4]
df02['month'] = df2['사용년월'].astype(str).str[-2:]
df02 = df02.drop(columns=['사용년월'])

# 5. 사용량(KWh)을 계산을 위해 숫자형으로 변환
df02['gas_amount'] = pd.to_numeric(df2['사용량(KWh)'], errors='coerce').fillna(0)

# 6. 필요한 컬럼만 선택
df02 = df02[['code', 'year', 'month', 'gas_amount']]
df02

              code  year month  gas_amount
0       10100-1-22  2021    01        1025
1       10100-1-22  2021    02        1348
2       10100-1-22  2021    03        1230
3       10100-1-22  2021    04         952
4       10100-1-22  2021    05         661
...            ...   ...   ...         ...
30733  32025-18-11  2021    08       24178
30734  32025-18-11  2021    09       25963
30735  32025-18-11  2021    10       42493
30736  32025-18-11  2021    11       93555
30737  32025-18-11  2021    12      155554

[30738 rows x 4 columns]

In [8]:
df02.to_csv('gas_code_2021.csv', index=False, encoding='utf-8-sig')

In [9]:
# df02 = df02.groupby(['code'], as_index=False)['gas_amount'].sum()
# df02

### 2022년도 데이터

In [10]:
df3 = pd.read_csv('./gas_2022.csv')
df3.columns = df3.columns.str.strip()
df3

                           대지위치  법정동코드   번   지    사용년월  사용량(KWh)
0          경상북도 포항시 남구 상도동 1-22  10100   1  22  202201      1946
1          경상북도 포항시 남구 상도동 1-22  10100   1  22  202202      2184
2          경상북도 포항시 남구 상도동 1-22  10100   1  22  202203      1785
3          경상북도 포항시 남구 상도동 1-22  10100   1  22  202204      1114
4          경상북도 포항시 남구 상도동 1-22  10100   1  22  202205       666
...                         ...    ...  ..  ..     ...       ...
32124  경상북도 포항시 남구 동해면 석리 18-11  32025  18  11  202208     21803
32125  경상북도 포항시 남구 동해면 석리 18-11  32025  18  11  202209     30111
32126  경상북도 포항시 남구 동해면 석리 18-11  32025  18  11  202210     50142
32127  경상북도 포항시 남구 동해면 석리 18-11  32025  18  11  202211     85158
32128  경상북도 포항시 남구 동해면 석리 18-11  32025  18  11  202212    170268

[32129 rows x 6 columns]

In [11]:
# 1. '대지위치' 컬럼 삭제
df03 = df3.drop(columns=['대지위치'])

# 2. 법정동코드 + 번 + 지 를 합쳐서 'code' 컬럼 생성
# 문자열 연산을 통해 하나로 합칩니다.
df03['code'] = df3['법정동코드'].astype(str) + '-' + \
                     df3['번'].astype(str) + '-' + \
                     df3['지'].astype(str)
    
# 3. 합치기에 사용된 기존 컬럼 삭제 (선택 사항)
df03 = df03.drop(columns=['법정동코드', '번', '지'])

# 4. 사용년월에서 month 추출 및 사용년월(year 포함) 삭제
# 문자열로 변환 후 뒤에서 두 자리만 가져옵니다.
df03['year'] = df3['사용년월'].astype(str).str[:4]
df03['month'] = df3['사용년월'].astype(str).str[-2:]
df03 = df03.drop(columns=['사용년월'])

# 5. 사용량(KWh)을 계산을 위해 숫자형으로 변환
df03['gas_amount'] = pd.to_numeric(df3['사용량(KWh)'], errors='coerce').fillna(0)

# 6. 필요한 컬럼만 선택
df03 = df03[['code', 'year', 'month', 'gas_amount']]
df03

              code  year month  gas_amount
0       10100-1-22  2022    01        1946
1       10100-1-22  2022    02        2184
2       10100-1-22  2022    03        1785
3       10100-1-22  2022    04        1114
4       10100-1-22  2022    05         666
...            ...   ...   ...         ...
32124  32025-18-11  2022    08       21803
32125  32025-18-11  2022    09       30111
32126  32025-18-11  2022    10       50142
32127  32025-18-11  2022    11       85158
32128  32025-18-11  2022    12      170268

[32129 rows x 4 columns]

In [12]:
df03.to_csv('gas_code_2022.csv', index=False, encoding='utf-8-sig')

In [13]:
# df03 = df03.groupby(['code'], as_index=False)['gas_amount'].sum()
# df03

### 2023년도 데이터

In [14]:
df4 = pd.read_csv('./gas_2023.csv')
df4.columns = df4.columns.str.strip()
df4

                            대지위치  법정동코드   번   지    사용년월  사용량(KWh)
0           경상북도 포항시 남구 상도동 1-22  10100   1  22  202301      1973
1           경상북도 포항시 남구 상도동 1-22  10100   1  22  202302      1925
2           경상북도 포항시 남구 상도동 1-22  10100   1  22  202303      1461
3           경상북도 포항시 남구 상도동 1-22  10100   1  22  202304       820
4           경상북도 포항시 남구 상도동 1-22  10100   1  22  202305       611
...                          ...    ...  ..  ..     ...       ...
33596  경상북도 포항시 남구 동해면 공당리 산16-1  32034  16   1  202308      5440
33597  경상북도 포항시 남구 동해면 공당리 산16-1  32034  16   1  202309      5904
33598  경상북도 포항시 남구 동해면 공당리 산16-1  32034  16   1  202310     12322
33599  경상북도 포항시 남구 동해면 공당리 산16-1  32034  16   1  202311     29391
33600  경상북도 포항시 남구 동해면 공당리 산16-1  32034  16   1  202312     58699

[33601 rows x 6 columns]

In [15]:
# 1. '대지위치' 컬럼 삭제
df04 = df4.drop(columns=['대지위치'])

# 2. 법정동코드 + 번 + 지 를 합쳐서 'code' 컬럼 생성
# 문자열 연산을 통해 하나로 합칩니다.
df04['code'] = df4['법정동코드'].astype(str) + '-' + \
                     df4['번'].astype(str) + '-' + \
                     df4['지'].astype(str)
    
# 3. 합치기에 사용된 기존 컬럼 삭제 (선택 사항)
df04 = df04.drop(columns=['법정동코드', '번', '지'])

# 4. 사용년월에서 month 추출 및 사용년월(year 포함) 삭제
# 문자열로 변환 후 뒤에서 두 자리만 가져옵니다.
df04['year'] = df4['사용년월'].astype(str).str[:4]
df04['month'] = df4['사용년월'].astype(str).str[-2:]
df04 = df04.drop(columns=['사용년월'])

# 5. 사용량(KWh)을 계산을 위해 숫자형으로 변환
df04['gas_amount'] = pd.to_numeric(df4['사용량(KWh)'], errors='coerce').fillna(0)

# 6. 필요한 컬럼만 선택
df04 = df04[['code', 'year', 'month', 'gas_amount']]
df04

             code  year month  gas_amount
0      10100-1-22  2023    01        1973
1      10100-1-22  2023    02        1925
2      10100-1-22  2023    03        1461
3      10100-1-22  2023    04         820
4      10100-1-22  2023    05         611
...           ...   ...   ...         ...
33596  32034-16-1  2023    08        5440
33597  32034-16-1  2023    09        5904
33598  32034-16-1  2023    10       12322
33599  32034-16-1  2023    11       29391
33600  32034-16-1  2023    12       58699

[33601 rows x 4 columns]

In [16]:
df04.to_csv('gas_code_2023.csv', index=False, encoding='utf-8-sig')

In [17]:
# df04 = df04.groupby(['code'], as_index=False)['gas_amount'].sum()
# df04

### 2024년도 데이터

In [18]:
df5 = pd.read_csv('./gas_2024.csv')
df5.columns = df5.columns.str.strip()
df5

                            대지위치  법정동코드   번   지    사용년월  사용량(KWh)
0           경상북도 포항시 남구 상도동 1-22  10100   1  22  202401      1519
1           경상북도 포항시 남구 상도동 1-22  10100   1  22  202402      1942
2           경상북도 포항시 남구 상도동 1-22  10100   1  22  202403      2152
3           경상북도 포항시 남구 상도동 1-22  10100   1  22  202404      2019
4           경상북도 포항시 남구 상도동 1-22  10100   1  22  202405      1169
...                          ...    ...  ..  ..     ...       ...
34886  경상북도 포항시 남구 동해면 공당리 산16-1  32034  16   1  202408      7409
34887  경상북도 포항시 남구 동해면 공당리 산16-1  32034  16   1  202409      7109
34888  경상북도 포항시 남구 동해면 공당리 산16-1  32034  16   1  202410     16727
34889  경상북도 포항시 남구 동해면 공당리 산16-1  32034  16   1  202411     35632
34890  경상북도 포항시 남구 동해면 공당리 산16-1  32034  16   1  202412     82029

[34891 rows x 6 columns]

In [19]:
# 1. '대지위치' 컬럼 삭제
df05 = df5.drop(columns=['대지위치'])

# 2. 법정동코드 + 번 + 지 를 합쳐서 'code' 컬럼 생성
# 문자열 연산을 통해 하나로 합칩니다.
df05['code'] = df5['법정동코드'].astype(str) + '-' + \
                     df5['번'].astype(str) + '-' + \
                     df5['지'].astype(str)
    
# 3. 합치기에 사용된 기존 컬럼 삭제 (선택 사항)
df05 = df05.drop(columns=['법정동코드', '번', '지'])

# 4. 사용년월에서 month 추출 및 사용년월(year 포함) 삭제
# 문자열로 변환 후 뒤에서 두 자리만 가져옵니다.
df05['year'] = df5['사용년월'].astype(str).str[:4]
df05['month'] = df5['사용년월'].astype(str).str[-2:]
df05 = df05.drop(columns=['사용년월'])

# 5. 사용량(KWh)을 계산을 위해 숫자형으로 변환
df05['gas_amount'] = pd.to_numeric(df5['사용량(KWh)'], errors='coerce').fillna(0)

# 6. 필요한 컬럼만 선택
df05 = df05[['code', 'year', 'month', 'gas_amount']]
df05

             code  year month  gas_amount
0      10100-1-22  2024    01        1519
1      10100-1-22  2024    02        1942
2      10100-1-22  2024    03        2152
3      10100-1-22  2024    04        2019
4      10100-1-22  2024    05        1169
...           ...   ...   ...         ...
34886  32034-16-1  2024    08        7409
34887  32034-16-1  2024    09        7109
34888  32034-16-1  2024    10       16727
34889  32034-16-1  2024    11       35632
34890  32034-16-1  2024    12       82029

[34891 rows x 4 columns]

In [20]:
df05.to_csv('gas_code_2024.csv', index=False, encoding='utf-8-sig')

In [21]:
# df05 = df05.groupby(['code'], as_index=False)['gas_amount'].sum()
# df05

### 2025년도 데이터

In [22]:
df6 = pd.read_csv('./gas_2025.csv')
df6.columns = df6.columns.str.strip()
df6

                            대지위치  법정동코드   번   지    사용년월  사용량(KWh)
0           경상북도 포항시 남구 상도동 1-22  10100   1  22  202501      1741
1           경상북도 포항시 남구 상도동 1-22  10100   1  22  202502      2642
2           경상북도 포항시 남구 상도동 1-22  10100   1  22  202503      3229
3           경상북도 포항시 남구 상도동 1-22  10100   1  22  202504      1380
4           경상북도 포항시 남구 상도동 1-22  10100   1  22  202505       575
...                          ...    ...  ..  ..     ...       ...
32332  경상북도 포항시 남구 동해면 공당리 산16-1  32034  16   1  202507     10092
32333  경상북도 포항시 남구 동해면 공당리 산16-1  32034  16   1  202508     10197
32334  경상북도 포항시 남구 동해면 공당리 산16-1  32034  16   1  202509      7980
32335  경상북도 포항시 남구 동해면 공당리 산16-1  32034  16   1  202510     14393
32336  경상북도 포항시 남구 동해면 공당리 산16-1  32034  16   1  202511     37960

[32337 rows x 6 columns]

In [23]:
# 1. '대지위치' 컬럼 삭제
df06 = df6.drop(columns=['대지위치'])

# 2. 법정동코드 + 번 + 지 를 합쳐서 'code' 컬럼 생성
# 문자열 연산을 통해 하나로 합칩니다.
df06['code'] = df6['법정동코드'].astype(str) + '-' + \
                     df6['번'].astype(str) + '-' + \
                     df6['지'].astype(str)
    
# 3. 합치기에 사용된 기존 컬럼 삭제 (선택 사항)
df06 = df06.drop(columns=['법정동코드', '번', '지'])

# 4. 사용년월에서 month 추출 및 사용년월(year 포함) 삭제
# 문자열로 변환 후 뒤에서 두 자리만 가져옵니다.
df06['year'] = df6['사용년월'].astype(str).str[:4]
df06['month'] = df6['사용년월'].astype(str).str[-2:]
df06 = df06.drop(columns=['사용년월'])

# 5. 사용량(KWh)을 계산을 위해 숫자형으로 변환
df06['gas_amount'] = pd.to_numeric(df6['사용량(KWh)'], errors='coerce').fillna(0)

# 6. 필요한 컬럼만 선택
df06 = df06[['code', 'year', 'month', 'gas_amount']]
df06

             code  year month  gas_amount
0      10100-1-22  2025    01        1741
1      10100-1-22  2025    02        2642
2      10100-1-22  2025    03        3229
3      10100-1-22  2025    04        1380
4      10100-1-22  2025    05         575
...           ...   ...   ...         ...
32332  32034-16-1  2025    07       10092
32333  32034-16-1  2025    08       10197
32334  32034-16-1  2025    09        7980
32335  32034-16-1  2025    10       14393
32336  32034-16-1  2025    11       37960

[32337 rows x 4 columns]

In [24]:
df06.to_csv('gas_code_2025.csv', index=False, encoding='utf-8-sig')

In [25]:
# df06 = df06.groupby(['code'], as_index=False)['gas_amount'].sum()
# df06