In [1]:
import warnings
warnings.filterwarnings('ignore')

## [문제] 인터넷 신규 가입 여부 예측 하는 예제를 구현하시오.  

#### 제출할 파일명: 홍길동_0429_정확도.ipynb  

#### <처리 조건>
- logistic regression 모델을 사용한다.
- 데이터 로드 : pd.read_csv('newbie.csv') 
- 종속 변수 : 'Newbie'
- 독립 변수 제거 : 'who', 'Country', 'Years on Internet‘
- 결측값 처리 :
	- Age : 평균으로 채움
	- Household Income, Sexual Preference, Marital Status : 최빈값으로 채움
- 범주형 독립변수 원핫인코딩 처리 : pd.get_dummies() 사용
- test 데이터 사이즈는 20%, train 데이터는 80%로 한다.(train_test_split 사용할것)
- 최종적으로 모델을 만든 후 정확도(accuracy)를 출력하도록 한다.

#### 데이터 로드

In [2]:
import pandas as pd

newbie = pd.read_csv('newbie.csv')
newbie.head(50)

,who,Newbie,Age,Gender,Household Income,Sexual Preference,Country,Education Attainment,Major Occupation,Marital Status,Years on Internet
0,id74364,0,54.0,Male,$50-74,Gay male,Ontario,Some College,Computer,Other,4-6 yr
1,id84505,0,39.0,Female,Over $100,Heterosexual,Sweden,Professional,Other,Other,1-3 yr
2,id84509,1,49.0,Female,$40-49,Heterosexual,Washington,Some College,Management,Other,Under 6 mo
3,id87028,1,22.0,Female,$40-49,Heterosexual,Florida,Some College,Computer,Married,6-12 mo
4,id76087,0,20.0,Male,$30-39,Bisexual,New Jersey,Some College,Education,Single,1-3 yr
5,id77190,0,16.0,Male,NaN,Heterosexual,New York,Grammar,Education,Single,1-3 yr
6,id78923,0,67.0,Male,$30-39,Heterosexual,New Jersey,Other,Other,Married,1-3 yr
7,id78976,0,25.0,Male,Under $10,Heterosexual,Connecticut,College,Education,Single,1-3 yr
8,id89941,0,54.0,Male,$75-99,Heterosexual,Washington,Professional,Professional,Married,4-6 yr
9,id75957,1,48.0,Female,$50-74,Heterosexual,Ohio,College,Education,Married,Under 6 mo
10,id76313,0,25.0,Male,$30-39,Heterosexual,Ontario,College,Computer,Single,1-3 yr
11,id80575,0,27.0,Female,$40-49,Bisexual,Wisconsin,College,Education,Single,4-6 yr
12,id87146,1,42.0,Male,$50-74,Heterosexual,Michigan,Some College,Management,Married,6-12 mo
13,id88233,1,48.0,Male,$20-29,Heterosexual,United Kingdom,Some College,Computer,Married,Under 6 mo
14,id72594,0,43.0,Male,$40-49,Heterosexual,Ontario,Some College,Computer,Married,1-3 yr
15,id81750,0,37.0,Male,Over $100,Heterosexual,Washington D.C.,Professional,Professional,Married,Over 7 yr
16,id84525,0,30.0,Male,Over $100,Heterosexual,Texas,College,Computer,Single,1-3 yr
17,id75960,0,25.0,Female,$40-49,Heterosexual,Texas,Special,Professional,Other,1-3 yr
18,id75085,0,40.0,Male,Over $100,Heterosexual,Florida,Professional,Computer,Single,4-6 yr
19,id84528,0,35.0,Male,NaN,Heterosexual,Wisconsin,Some College,Computer,Married,4-6 yr
20,id81669,0,26.0,Male,Over $100,Heterosexual,Texas,College,Computer,Married,Over 7 yr
21,id85191,1,36.0,Female,$50-74,Heterosexual,Florida,Some College,Professional,Married,6-12 mo
22,id87151,0,24.0,Male,$30-39,Heterosexual,Australia,Some College,Education,Single,1-3 yr
23,id89679,0,27.0,Male,$20-29,Heterosexual,California,Masters,Computer,Single,1-3 yr
24,id72605,0,15.0,Male,NaN,Heterosexual,Iowa,High School,Education,Single,1-3 yr
25,id80272,0,31.0,Male,NaN,Heterosexual,California,College,Computer,Single,Over 7 yr
26,id84535,0,37.0,Female,$50-74,Heterosexual,Arizona,College,Computer,Married,1-3 yr
27,id82732,0,28.0,Male,$20-29,Heterosexual,California,Doctoral,Professional,Single,Over 7 yr
28,id74703,0,23.0,Female,$20-29,Heterosexual,Ohio,Some College,Computer,Single,1-3 yr
29,id77419,0,50.0,Female,Over $100,Heterosexual,Pennsylvania,College,Computer,Married,4-6 yr
30,id79513,0,38.0,Male,$75-99,Transgender,California,College,Computer,Single,Over 7 yr
31,id80149,0,23.0,Male,$50-74,Heterosexual,United Kingdom,Masters,Computer,Other,4-6 yr
32,id89887,0,48.0,Male,$50-74,NaN,Wisconsin,Some College,Computer,Married,1-3 yr
33,id74862,0,30.0,Male,$50-74,Heterosexual,France,College,Computer,Single,1-3 yr
34,id72593,0,42.0,Male,$50-74,Heterosexual,Hong Kong,College,Management,Married,1-3 yr
35,id84537,0,32.0,Male,$50-74,Heterosexual,Washington,Special,Computer,Married,1-3 yr
36,id88487,0,48.0,Female,$40-49,Heterosexual,Washington,College,Computer,Divorced,4-6 yr
37,id72602,0,26.0,Male,$40-49,Heterosexual,Washington,Doctoral,Computer,Single,Over 7 yr
38,id78506,0,20.0,Male,$10-19,Gay male,Florida,Some College,Education,Other,4-6 yr
39,id72609,0,42.0,Female,NaN,Heterosexual,Florida,Special,Professional,Divorced,1-3 yr
40,id76937,0,27.0,Male,$50-74,Heterosexual,Florida,Masters,Professional,Married,4-6 yr
41,id88303,0,26.0,Male,$75-99,Heterosexual,United Kingdom,Some College,Computer,Married,1-3 yr
42,id7274,0,NaN,Female,NaN,Heterosexual,California,Masters,Professional,Single,4-6 yr
43,id84540,0,54.0,Female,$75-99,Heterosexual,New York,Doctoral,Education,Married,1-3 yr
44,id84981,0,34.0,Male,$20-29,Gay male,Texas,Some College,Professional,Other,1-3 yr
45,id72903,0,47.0,Male,$20-29,NaN,Florida,Some College,Management,Married,1-3 yr
46,id84541,0,63.0,Male,$30-39,Heterosexual,Texas,Professional,Professional,Married,1-3 yr
47,id72509,0,27.0,Male,$10-19,Heterosexual,Georgia,College,Education,Married,4-6 yr
48,id79696,0,19.0,Female,Over $100,Heterosexual,Missouri,Some College,Education,Single,1-3 yr
49,id84378,0,26.0,Female,$40-49,Heterosexual,Georgia,Masters,Management,Single,1-3 yr

#### 독립 변수 제거

In [3]:
newbie = newbie.drop(['who', 'Country', 'Years on Internet'], axis=1)
newbie.head(2)

,Newbie,Age,Gender,Household Income,Sexual Preference,Education Attainment,Major Occupation,Marital Status
0,0,54.0,Male,$50-74,Gay male,Some College,Computer,Other
1,0,39.0,Female,Over $100,Heterosexual,Professional,Other,Other

#### 결측값 처리

In [4]:
from sklearn.impute import SimpleImputer
import numpy as np

imp_mean = SimpleImputer(missing_values=np.nan, strategy='mean')
age_mean = imp_mean.fit_transform(newbie[['Age']])

newbie['Age'] = age_mean
newbie.head(50)

,Newbie,Age,Gender,Household Income,Sexual Preference,Education Attainment,Major Occupation,Marital Status
0,0,54.000000,Male,$50-74,Gay male,Some College,Computer,Other
1,0,39.000000,Female,Over $100,Heterosexual,Professional,Other,Other
2,1,49.000000,Female,$40-49,Heterosexual,Some College,Management,Other
3,1,22.000000,Female,$40-49,Heterosexual,Some College,Computer,Married
4,0,20.000000,Male,$30-39,Bisexual,Some College,Education,Single
5,0,16.000000,Male,NaN,Heterosexual,Grammar,Education,Single
6,0,67.000000,Male,$30-39,Heterosexual,Other,Other,Married
7,0,25.000000,Male,Under $10,Heterosexual,College,Education,Single
8,0,54.000000,Male,$75-99,Heterosexual,Professional,Professional,Married
9,1,48.000000,Female,$50-74,Heterosexual,College,Education,Married
10,0,25.000000,Male,$30-39,Heterosexual,College,Computer,Single
11,0,27.000000,Female,$40-49,Bisexual,College,Education,Single
12,1,42.000000,Male,$50-74,Heterosexual,Some College,Management,Married
13,1,48.000000,Male,$20-29,Heterosexual,Some College,Computer,Married
14,0,43.000000,Male,$40-49,Heterosexual,Some College,Computer,Married
15,0,37.000000,Male,Over $100,Heterosexual,Professional,Professional,Married
16,0,30.000000,Male,Over $100,Heterosexual,College,Computer,Single
17,0,25.000000,Female,$40-49,Heterosexual,Special,Professional,Other
18,0,40.000000,Male,Over $100,Heterosexual,Professional,Computer,Single
19,0,35.000000,Male,NaN,Heterosexual,Some College,Computer,Married
20,0,26.000000,Male,Over $100,Heterosexual,College,Computer,Married
21,1,36.000000,Female,$50-74,Heterosexual,Some College,Professional,Married
22,0,24.000000,Male,$30-39,Heterosexual,Some College,Education,Single
23,0,27.000000,Male,$20-29,Heterosexual,Masters,Computer,Single
24,0,15.000000,Male,NaN,Heterosexual,High School,Education,Single
25,0,31.000000,Male,NaN,Heterosexual,College,Computer,Single
26,0,37.000000,Female,$50-74,Heterosexual,College,Computer,Married
27,0,28.000000,Male,$20-29,Heterosexual,Doctoral,Professional,Single
28,0,23.000000,Female,$20-29,Heterosexual,Some College,Computer,Single
29,0,50.000000,Female,Over $100,Heterosexual,College,Computer,Married
30,0,38.000000,Male,$75-99,Transgender,College,Computer,Single
31,0,23.000000,Male,$50-74,Heterosexual,Masters,Computer,Other
32,0,48.000000,Male,$50-74,NaN,Some College,Computer,Married
33,0,30.000000,Male,$50-74,Heterosexual,College,Computer,Single
34,0,42.000000,Male,$50-74,Heterosexual,College,Management,Married
35,0,32.000000,Male,$50-74,Heterosexual,Special,Computer,Married
36,0,48.000000,Female,$40-49,Heterosexual,College,Computer,Divorced
37,0,26.000000,Male,$40-49,Heterosexual,Doctoral,Computer,Single
38,0,20.000000,Male,$10-19,Gay male,Some College,Education,Other
39,0,42.000000,Female,NaN,Heterosexual,Special,Professional,Divorced
40,0,27.000000,Male,$50-74,Heterosexual,Masters,Professional,Married
41,0,26.000000,Male,$75-99,Heterosexual,Some College,Computer,Married
42,0,35.222269,Female,NaN,Heterosexual,Masters,Professional,Single
43,0,54.000000,Female,$75-99,Heterosexual,Doctoral,Education,Married
44,0,34.000000,Male,$20-29,Gay male,Some College,Professional,Other
45,0,47.000000,Male,$20-29,NaN,Some College,Management,Married
46,0,63.000000,Male,$30-39,Heterosexual,Professional,Professional,Married
47,0,27.000000,Male,$10-19,Heterosexual,College,Education,Married
48,0,19.000000,Female,Over $100,Heterosexual,Some College,Education,Single
49,0,26.000000,Female,$40-49,Heterosexual,Masters,Management,Single

In [5]:
imp_most = SimpleImputer(missing_values=np.nan, strategy='most_frequent')

HI_most = imp_most.fit_transform(newbie[['Household Income']])
HI_most_newbie = pd.DataFrame(HI_most)
newbie['Household Income'] = HI_most_newbie[0]

SP_most = imp_most.fit_transform(newbie[['Sexual Preference']])
SP_most_newbie = pd.DataFrame(SP_most)
newbie['Sexual Preference'] = SP_most_newbie[0]

MS_most = imp_most.fit_transform(newbie[['Marital Status']])
MS_most_newbie = pd.DataFrame(MS_most)
newbie['Marital Status'] = MS_most_newbie[0]

newbie.head(50)

,Newbie,Age,Gender,Household Income,Sexual Preference,Education Attainment,Major Occupation,Marital Status
0,0,54.000000,Male,$50-74,Gay male,Some College,Computer,Other
1,0,39.000000,Female,Over $100,Heterosexual,Professional,Other,Other
2,1,49.000000,Female,$40-49,Heterosexual,Some College,Management,Other
3,1,22.000000,Female,$40-49,Heterosexual,Some College,Computer,Married
4,0,20.000000,Male,$30-39,Bisexual,Some College,Education,Single
5,0,16.000000,Male,$50-74,Heterosexual,Grammar,Education,Single
6,0,67.000000,Male,$30-39,Heterosexual,Other,Other,Married
7,0,25.000000,Male,Under $10,Heterosexual,College,Education,Single
8,0,54.000000,Male,$75-99,Heterosexual,Professional,Professional,Married
9,1,48.000000,Female,$50-74,Heterosexual,College,Education,Married
10,0,25.000000,Male,$30-39,Heterosexual,College,Computer,Single
11,0,27.000000,Female,$40-49,Bisexual,College,Education,Single
12,1,42.000000,Male,$50-74,Heterosexual,Some College,Management,Married
13,1,48.000000,Male,$20-29,Heterosexual,Some College,Computer,Married
14,0,43.000000,Male,$40-49,Heterosexual,Some College,Computer,Married
15,0,37.000000,Male,Over $100,Heterosexual,Professional,Professional,Married
16,0,30.000000,Male,Over $100,Heterosexual,College,Computer,Single
17,0,25.000000,Female,$40-49,Heterosexual,Special,Professional,Other
18,0,40.000000,Male,Over $100,Heterosexual,Professional,Computer,Single
19,0,35.000000,Male,$50-74,Heterosexual,Some College,Computer,Married
20,0,26.000000,Male,Over $100,Heterosexual,College,Computer,Married
21,1,36.000000,Female,$50-74,Heterosexual,Some College,Professional,Married
22,0,24.000000,Male,$30-39,Heterosexual,Some College,Education,Single
23,0,27.000000,Male,$20-29,Heterosexual,Masters,Computer,Single
24,0,15.000000,Male,$50-74,Heterosexual,High School,Education,Single
25,0,31.000000,Male,$50-74,Heterosexual,College,Computer,Single
26,0,37.000000,Female,$50-74,Heterosexual,College,Computer,Married
27,0,28.000000,Male,$20-29,Heterosexual,Doctoral,Professional,Single
28,0,23.000000,Female,$20-29,Heterosexual,Some College,Computer,Single
29,0,50.000000,Female,Over $100,Heterosexual,College,Computer,Married
30,0,38.000000,Male,$75-99,Transgender,College,Computer,Single
31,0,23.000000,Male,$50-74,Heterosexual,Masters,Computer,Other
32,0,48.000000,Male,$50-74,Heterosexual,Some College,Computer,Married
33,0,30.000000,Male,$50-74,Heterosexual,College,Computer,Single
34,0,42.000000,Male,$50-74,Heterosexual,College,Management,Married
35,0,32.000000,Male,$50-74,Heterosexual,Special,Computer,Married
36,0,48.000000,Female,$40-49,Heterosexual,College,Computer,Divorced
37,0,26.000000,Male,$40-49,Heterosexual,Doctoral,Computer,Single
38,0,20.000000,Male,$10-19,Gay male,Some College,Education,Other
39,0,42.000000,Female,$50-74,Heterosexual,Special,Professional,Divorced
40,0,27.000000,Male,$50-74,Heterosexual,Masters,Professional,Married
41,0,26.000000,Male,$75-99,Heterosexual,Some College,Computer,Married
42,0,35.222269,Female,$50-74,Heterosexual,Masters,Professional,Single
43,0,54.000000,Female,$75-99,Heterosexual,Doctoral,Education,Married
44,0,34.000000,Male,$20-29,Gay male,Some College,Professional,Other
45,0,47.000000,Male,$20-29,Heterosexual,Some College,Management,Married
46,0,63.000000,Male,$30-39,Heterosexual,Professional,Professional,Married
47,0,27.000000,Male,$10-19,Heterosexual,College,Education,Married
48,0,19.000000,Female,Over $100,Heterosexual,Some College,Education,Single
49,0,26.000000,Female,$40-49,Heterosexual,Masters,Management,Single

#### 범주형 독립변수 원핫인코딩 처리

In [6]:
newbie = pd.get_dummies(newbie, columns=['Gender', 'Household Income', 'Sexual Preference',
                               'Education Attainment', 'Major Occupation', 'Marital Status'],
                       dtype='int')
newbie.head()

,Newbie,Age,Gender_Female,Gender_Male,Household Income_$10-19,Household Income_$20-29,Household Income_$30-39,Household Income_$40-49,Household Income_$50-74,Household Income_$75-99,...,Major Occupation_Education,Major Occupation_Management,Major Occupation_Other,Major Occupation_Professional,Marital Status_Divorced,Marital Status_Married,Marital Status_Other,Marital Status_Separated,Marital Status_Single,Marital Status_Widowed
0,0,54.0,0,1,0,0,0,0,1,0,...,0,0,0,0,0,0,1,0,0,0
1,0,39.0,1,0,0,0,0,0,0,0,...,0,0,1,0,0,0,1,0,0,0
2,1,49.0,1,0,0,0,0,1,0,0,...,0,1,0,0,0,0,1,0,0,0
3,1,22.0,1,0,0,0,0,1,0,0,...,0,0,0,0,0,1,0,0,0,0
4,0,20.0,0,1,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0

In [7]:
newbie.iloc[:, 1:]

,Age,Gender_Female,Gender_Male,Household Income_$10-19,Household Income_$20-29,Household Income_$30-39,Household Income_$40-49,Household Income_$50-74,Household Income_$75-99,Household Income_Over $100,...,Major Occupation_Education,Major Occupation_Management,Major Occupation_Other,Major Occupation_Professional,Marital Status_Divorced,Marital Status_Married,Marital Status_Other,Marital Status_Separated,Marital Status_Single,Marital Status_Widowed
0,54.0,0,1,0,0,0,0,1,0,0,...,0,0,0,0,0,0,1,0,0,0
1,39.0,1,0,0,0,0,0,0,0,1,...,0,0,1,0,0,0,1,0,0,0
2,49.0,1,0,0,0,0,1,0,0,0,...,0,1,0,0,0,0,1,0,0,0
3,22.0,1,0,0,0,0,1,0,0,0,...,0,0,0,0,0,1,0,0,0,0
4,20.0,0,1,0,0,1,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19578,22.0,0,1,0,0,0,0,0,0,1,...,1,0,0,0,0,0,0,0,1,0
19579,19.0,0,1,0,0,0,0,1,0,0,...,1,0,0,0,0,0,0,0,1,0
19580,49.0,1,0,0,0,0,0,1,0,0,...,1,0,0,0,0,1,0,0,0,0
19581,42.0,1,0,0,0,0,0,1,0,0,...,0,0,1,0,0,1,0,0,0,0
19582,24.0,1,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0

#### train 데이터, test 데이터 설정

In [118]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(newbie.iloc[:, 1:], newbie[['Newbie']],
                                                    test_size=0.2,
                                                    random_state=1000)

#### Logistic Regression (로지스틱 회귀)

In [119]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(solver='sag')
model.fit(X_train, y_train)

LogisticRegression(solver='sag')

In [120]:
score = model.score(X_test, y_test)
print(f'전체 데이터로 예측한 결과 : {score}')

전체 데이터로 예측한 결과 : 0.7638498851161604

In [121]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaler.fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

model = LogisticRegression(solver='liblinear')
model.fit(X_train_scaled, y_train)
score = model.score(X_test_scaled, y_test)
print(f'전체 데이터로 예측한 결과 : {score}')

전체 데이터로 예측한 결과 : 0.7641051825376564

In [122]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(X_train)
X_train_standard = scaler.transform(X_train)
X_test_standard = scaler.transform(X_test)

model = LogisticRegression(solver='liblinear')
model.fit(X_train_standard, y_train)
score = model.score(X_test_standard, y_test)
print(f'전체 데이터로 예측한 결과 : {score}')

전체 데이터로 예측한 결과 : 0.7633392902731683

#### for문 이용

In [128]:
from sklearn.model_selection import train_test_split

lst0 = []
for i in range(0, 1501):
    X_train, X_test, y_train, y_test = train_test_split(newbie.iloc[:, 1:], newbie[['Newbie']],
                                                        test_size=0.2,
                                                        random_state=i)
    model = LogisticRegression(solver='sag')
    model.fit(X_train, y_train)
    score = model.score(X_test, y_test)
    lst0.append(score)

print(max(lst0))

0.7806995149348992

In [131]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

lst1 = []
for i in range(0, 1501):
    X_train, X_test, y_train, y_test = train_test_split(newbie.iloc[:, 1:], newbie[['Newbie']],
                                                        test_size=0.2,
                                                        random_state=i)
    scaler = MinMaxScaler()
    scaler.fit(X_train)
    X_train_scaled = scaler.transform(X_train)
    X_test_scaled = scaler.transform(X_test)
    
    model = LogisticRegression(solver='liblinear')
    model.fit(X_train_scaled, y_train)
    score1 = model.score(X_test_scaled, y_test)
    lst1.append(score1)

print(max(lst1))

0.7806995149348992

In [132]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

lst2 = []
for i in range(0, 1501):
    X_train, X_test, y_train, y_test = train_test_split(newbie.iloc[:, 1:], newbie[['Newbie']],
                                                        test_size=0.2,
                                                        random_state=i)
    scaler = StandardScaler()
    scaler.fit(X_train)
    X_train_standard = scaler.transform(X_train)
    X_test_standard = scaler.transform(X_test)
    
    model = LogisticRegression(solver='liblinear')
    model.fit(X_train_standard, y_train)
    score2 = model.score(X_test_standard, y_test)
    lst2.append(score2)

print(max(lst2))

0.7809548123563952

#### while문 사용

In [134]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

i = 1501
while i < 10001:
    X_train, X_test, y_train, y_test = train_test_split(newbie.iloc[:, 1:], newbie[['Newbie']],
                                                        test_size=0.2,
                                                        random_state=i)
    scaler = StandardScaler()
    scaler.fit(X_train)
    X_train_standard = scaler.transform(X_train)
    X_test_standard = scaler.transform(X_test)
    
    model = LogisticRegression(solver='liblinear')
    model.fit(X_train_standard, y_train)
    score3 = model.score(X_test_standard, y_test)
    if score3 > 0.7809:
        print('random_state :', i, 'accuracy :', score3)
    i += 1

random_state : 4280 accuracy : 0.7865713556293081
random_state : 4578 accuracy : 0.78580546336482
random_state : 9961 accuracy : 0.7817207046208833